mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("recipe/", include("recipe.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
# custom created, name convention should be followed
# For defining routing info

from django.urls import path

from . import views

# namespace
# defining namespace helps in referencing a path in href and other places.
app_name = "polls"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    # path("<int:question_id>/", views.detail, name="detail"),
    # Using Generic View
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # path("<int:question_id>/results/", views.results, name="results"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

recipe/urls.py
from django.urls import path

from .views import *

app_name='recipe'

urlpatterns = [
    path("", index, name="index"),
    path("delete_recipe/<int:id>", delete_recipe, name="delete_recipe"),
    path("update_recipe/<int:id>", update_recipe, name="update_recipe")
]

todo/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    """
        It’s important to add __str__() methods to your models, not only for your own convenience
        when dealing with the interactive prompt, but also because objects’ representations are used
        throughout Django’s automatically-generated admin.
    """
    def __str__(self):
        return self.question_text

    # helper function to later use in views or templates.
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("Date published")

class Choice(models.Model):
    def __str__(self):
        return self.choice_text

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default = 0)

recipe/models.py
from typing import override
from django.db import models

# Create your models here.

class Recipe(models.Model):

    @override
    def __str__(self):
        return self.recipe_name

    recipe_name = models.CharField(max_length=100)
    recipe_description = models.TextField(max_length=500)
    recipe_image = models.ImageField(upload_to="recipes")

polls/views.py
from django.db.models import F
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from polls.models import Question, Choice

# --- Hard Way of building index, detail and result ---
# def index(request):
#     latest_questions = Question.objects.order_by("-pub_date")[:5]  # get first 5 polls
#     template = loader.get_template("polls/index.html")
#     context = {"latest_question_list":latest_questions}
#     return HttpResponse(template.render(context,request))

# def detail(request, question_id):
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Invalid question id.")
    # return render(request,"polls/detail.html",{"question":question})  # shortcut for rendering

    # shortcut for searching object and throwing 404 if not found
    # question = get_object_or_404(Question, pk=question_id)
    # return render(request, "polls/detail.html", {"question":question})

# def results(request, question_id):
    # question = get_object_or_404(Question, pk=question_id)
    # return render(request, "polls/results.html", {"question": question})

# ---- Generic Views (provided by django for redundant and common cases)---
# For listing the objects based on a key
class IndexView(generic.ListView):
    # required otherwise, django will look for <app name>/<model name>_detail.html.
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"



def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

recipe/views.py
from django.db.models import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

# Create your views here.
from .models import Recipe

def index(request):
    if request.method == "POST":
        data = request.POST
        recipe_image = request.FILES.get('recipe_image')
        recipe_name = data.get('recipe_name')
        recipe_description = data.get('recipe_description')

        # save in db
        Recipe.objects.create(recipe_image=recipe_image,
            recipe_name=recipe_name,
            recipe_description=recipe_description
        )
        return redirect("recipe:index")
    recipes = Recipe.objects.all()

    search_query = request.GET.get('search')

    if search_query:
        recipes = recipes.filter(recipe_name__icontains=search_query)

    return render(request, "recipes/index.html", {'recipes':recipes})

def update_recipe(request, id):
    recipe = get_object_or_404(Recipe, pk=id)

    if request.method == "POST":

        data = request.POST
        image = request.FILES.get("recipe_image")
        recipe.recipe_name = data.get('recipe_name')
        recipe.recipe_description = data.get('recipe_description')

        if image:
            recipe.recipe_image = image
        recipe.save()
        return redirect("recipe:index")

    return render(request, "recipes/update.html", {"recipe":recipe})


def delete_recipe(request, id):
    try:
        recipe = Recipe.objects.get(pk=id)
    except Recipe.DoesNotExist:
        return render(request, "recipes/index.html", {"error_message":"Invalid recipe id"})
    else:
        recipe.delete()
        return redirect( "recipe:index")

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %} {# to prevent csrf #}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %} {% for choice in question.choice_set.all %}
        <input
            type="radio"
            name="choice"
            id="choice{{ forloop.counter }}"
            value="{{ choice.id }}"
        />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
        ><br />
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}"
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li>
        <!--Here we are using polls hardcoded, this makes it tightly coupled-->
        <!--<a href="/polls/{{ question.id }}/">{{ question.question_text }}</a>-->

        <!--Since, we have defined names in path() we can utilize it to replace appropriate url path-->
        <a href="{% url 'polls:detail' question.id %}"
            >{{ question.question_text}}</a
        >
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>
        {{ choice.choice_text }} -- {{ choice.votes }}
        <span></span>
        vote{{ choice.votes|pluralize }}
    </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

recipe/templates/base.html
<!doctype html>
<html lang="en">
    <link
        href="https://cdn.jsdelivr.net/npm/daisyui@5"
        rel="stylesheet"
        type="text/css"
    />
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link
        href="https://cdn.jsdelivr.net/npm/daisyui@5/themes.css"
        rel="stylesheet"
        type="text/css"
    />
    <title>{% block title %} Recipe App {% endblock %}</title>
    <body>
        <h1
            style="
                font-family: Arial, Helvetica, sans-serif;
                text-align: center;
                font-size: 2rem;
                font-weight: 600;
            "
        >
            Recipe Saver 📁
        </h1>
        {% block content %} {% endblock %}
    </body>
    <footer
        class="footer sm:footer-horizontal footer-center bg-base-300 text-base-content p-4"
    >
        <aside>
            <p
                style="
                    background-color: grey;
                    color: white;
                    padding: 10px;
                    border-radius: 10px;
                "
            >
                Built with <span style="color: springgreen">Django</span> by
                Pradeep
            </p>
        </aside>
    </footer>
</html>

recipe/templates/recipes/index.html
{% extends "base.html" %} {% block title %} Recipe | Home{% endblock %}
<span></span>
{% block content %}

<div class="bg-base-100 px-10 shrink-0 shadow-2xl">
    {% if error_message %}
    <div role="alert" class="alert alert-error">
        <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6 shrink-0 stroke-current"
            fill="none"
            viewBox="0 0 24 24"
        >
            <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"
            />
        </svg>
        <span>{{error_message}}</span>
    </div>
    {% endif %}
    <form
        class="card-body max-w-md mx-auto"
        method="post"
        enctype="multipart/form-data"
    >
        {% csrf_token %}
        <fieldset class="fieldset space-y-3">
            <label class="label">Recipe Name</label>
            <input
                type="text"
                class="input w-full"
                placeholder="Recipe Name"
                name="recipe_name"
            />

            <label class="label">Recipe Description</label>
            <textarea
                class="textarea w-full"
                placeholder="Recipe Description"
                name="recipe_description"
            ></textarea>

            <label class="label">Recipe Image</label>
            <input type="file" class="file-input w-full" name="recipe_image" />

            <!-- Button is centered and not full width -->
            <button
                class="btn btn-neutral w-auto self-center mt-4"
                type="submit"
            >
                Submit
            </button>
        </fieldset>
    </form>
    <div class="divider"></div>
    <form class="flex justify-center py-8">
        <label class="input w-full max-w-md">
            <svg
                class="h-[1em] opacity-50"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
            >
                <g
                    stroke-linejoin="round"
                    stroke-linecap="round"
                    stroke-width="2.5"
                    fill="none"
                    stroke="currentColor"
                >
                    <circle cx="11" cy="11" r="8"></circle>
                    <path d="m21 21-4.3-4.3"></path>
                </g>
            </svg>

            <input
                type="search"
                placeholder="Search"
                name="search"
                class="grow"
            />
        </label>
        <button class="btn btn-soft btn-primary mx-8" type="submit">
            Search
        </button>
    </form>

    <div
        class="overflow-x-auto rounded-box border border-base-content/5 bg-base-100"
    >
        <table class="table">
            <!-- head -->
            <thead>
                <tr>
                    <th>S. No.</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Image</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for recipe in recipes %}
                <tr>
                    <th>{{ forloop.counter }}</th>
                    <td>{{ recipe.recipe_name }}</td>
                    <td>{{ recipe.recipe_description}}</td>
                    <td>
                        <img
                            src="/media/{{recipe.recipe_image}}"
                            alt="{{recipe.recipe_name}} image"
                            style="height: 100px"
                        />
                    </td>
                    <td>
                        <a
                            href="{% url 'recipe:delete_recipe' recipe.id %}"
                            class="btn btn-soft btn-error"
                            >Delete</a
                        >
                    </td>
                    <td>
                        <a
                            href="{% url 'recipe:update_recipe' recipe.id %}"
                            class="btn btn-soft btn-success"
                            >Update</a
                        >
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

recipe/templates/recipes/update.html
{% extends "base.html" %} {% block title %} Update | Recipe {% endblock %}
<span></span>
{% block content %}

<div class="max-w-md mx-auto mt-8 p-6 bg-base-100 shadow-xl rounded-xl">
    <form method="post" enctype="multipart/form-data" class="space-y-4">
        {% csrf_token %}

        <div class="form-control">
            <label class="label">Recipe Name</label>
            <input
                type="text"
                class="input input-bordered w-full"
                placeholder="Recipe Name"
                name="recipe_name"
                value="{{ recipe.recipe_name }}"
            />
        </div>

        <div class="form-control">
            <label class="label">Recipe Description</label>
            <textarea
                class="textarea textarea-bordered w-full"
                placeholder="Recipe Description"
                name="recipe_description"
            >
{{ recipe.recipe_description }}</textarea
            >
        </div>

        <div class="form-control">
            <label class="label">Recipe Image</label>
            <input
                type="file"
                class="file-input file-input-bordered w-full"
                name="recipe_image"
            />
        </div>

        <!-- Center the button -->
        <div class="flex justify-center">
            <button class="btn btn-neutral" type="submit">Submit</button>
        </div>
    </form>
</div>

{% endblock %}